// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlXjjwoGzEJuSm_Zvoi3p9XHqHtip9Mgs',
    appId: '1:365762963805:web:962796e7d42c1ad1eca0b4',
    messagingSenderId: '365762963805',
    projectId: 'vize-030121008',
    authDomain: 'vize-030121008.firebaseapp.com',
    storageBucket: 'vize-030121008.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2SegVUwLIrNTxWDCwtDWImaq2hdx9Das',
    appId: '1:365762963805:android:4a486af25ab27d43eca0b4',
    messagingSenderId: '365762963805',
    projectId: 'vize-030121008',
    storageBucket: 'vize-030121008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDulSFQqPg_NO-RVgzeYgSDfjfKOZQV99A',
    appId: '1:365762963805:ios:28c28ca7dc317a88eca0b4',
    messagingSenderId: '365762963805',
    projectId: 'vize-030121008',
    storageBucket: 'vize-030121008.appspot.com',
    iosClientId: '365762963805-58sn9f03n4vv80sjgbgpkvaml7ssokvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDulSFQqPg_NO-RVgzeYgSDfjfKOZQV99A',
    appId: '1:365762963805:ios:28c28ca7dc317a88eca0b4',
    messagingSenderId: '365762963805',
    projectId: 'vize-030121008',
    storageBucket: 'vize-030121008.appspot.com',
    iosClientId: '365762963805-58sn9f03n4vv80sjgbgpkvaml7ssokvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
